version: '3'

services:

  unit:
    build:
      context: docker/dockerfiles/centos/centos5/
      dockerfile: Dockerfile
    volumes:
      - ${PWD}:/repo
    working_dir: /repo
    command: bash -c "make test"

