version: '3'

services:

  release:
    build:
      context: .
      dockerfile: docker/dockerfiles/goreleaser/Dockerfile
    working_dir: /repo/src
    environment:
      - AWS_REGION=$AWS_REGION
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    command: bash -c "GITHUB_TOKEN=`aws ssm get-parameters --names 'github_token' --region $AWS_REGION --query 'Parameters[0].Value' --output text`; export GITHUB_TOKEN; goreleaser release --config=/.goreleaser.yml --rm-dist --snapshot"
