version: '3'

services:

  unit:
    build:
      context: docker/dockerfiles/centos/centos5/
      dockerfile: Dockerfile
    volumes:
      - ${PWD}:/go/src/github.com/newrelic/nri-nginx/
    working_dir: /go/src/github.com/newrelic/nri-nginx/
    command: bash -c "export PATH=$PATH:/root/go/bin; make integration-test"

