version: '3'

services:

  release:
    build:
      context: .
      dockerfile: docker/dockerfiles/goreleaser/Dockerfile
    working_dir: /repo/src
    command: bash -c "sleep 10000; goreleaser release --config=/.goreleaser.yml --rm-dist"