version: '3'

services:

  unit:
    build: docker/dockerfiles/windows/nanoserver
    working_dir: c:/go/src/github.com/newrelic/nri-nginx/
    volumes:
      - . :c:/go/src/github.com/newrelic/nri-nginx/
    command: "go test -v"

