version: '3'

services:

  unit:
    build:
      context: docker/dockerfiles/centos/centos5/
      dockerfile: Dockerfile
    volumes:
      - ${PWD}:/go/src/github.com/jportasa/nri-nginx/
    working_dir: /go/src/github.com/jportasa/nri-nginx/
    command: bash -c "export GOPATH=/go/; export PATH=$PATH:/root/go/bin; make test"

