version: '3'

services:

  unit:
    build: docker/dockerfiles/centos/centos5
      context: .
      dockerfile: docker/dockerfiles/centos/centos5
    volumes:
      - .:/go/src/github.com/newrelic/nri-nginx/
    working_dir: /go/src/github.com/newrelic/nri-nginx/
    command: bash -c "go test -v"

