name: Create Binaries and push to GH
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  tags:
    - *

jobs:
  build-binaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create binaries
        env:
          AWS_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          docker-compose --file docker_compose_goreleaser.yml run release
          

