name: Unit tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: image

#jobs:
#  Test-go-centos:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Run Go tests in Centos 5
#        run: |
#          docker-compose --file docker_compose_test_centos5.yml run unit

#  Test-go-windows:
#    runs-on: windows-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Run Go tests in Windows Nanoserver
#        run: |
#          docker-compose --file  docker_compose_test_windows.yml run unit

on: push

jobs:
  test:
    runs-on: windows-2019
    steps:
      - name: Install Chocolatey PowerShell Module
        shell: powershell
        run: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
      - name: Checkout
        uses: actions/checkout@v2
      - name: Choco help
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: -h