name: Tests Integration
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        env:
          GO_VERSION: 1.14
        run: |
          curl -O https://dl.google.com/go/go$GO_VERSION.linux-amd64.tar.gz
          tar -xf go$GO_VERSION.linux-amd64.tar.gz
          pwd
          export GOPATH=${PWD}
          export GOROOT=${PWD}/go
          make integration-test

