name: Tests Integration
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'true'
          go-version: '1.14'
      - name: Integration Tests
        run: |
         export GOPATH=${PWD}
         echo "GOPATH: $GOPATH"
         echo "GOROOT: $GOROOT"
         echo "Current dir: ${PWD}"
         ls -la
         go get ./...
         make integration-test








